name: Build image and SLSA L3 provenance (no push)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
env:
  IMAGE_NAME: atitest
  IMAGE_TAG: test-slsa

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      image: ${{ env.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build image locally (no push)
        id: build
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag "${IMAGE_NAME}:${IMAGE_TAG}" \
            --provenance=false \
            --output=type=docker \
            .
          digest=$(docker image inspect "${IMAGE_NAME}:${IMAGE_TAG}" --format='{{index .RepoDigests 0}}' | cut -d'@' -f2)
          echo "digest=$digest" >> $GITHUB_OUTPUT

  generate-provenance:
    needs: build-image
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.build-image.outputs.image }}
      digest: ${{ needs.build-image.outputs.digest }}
      upload-artifact: true    # save .intoto.jsonl as workflow artifact
    secrets: inherit           # pass OIDC and repo secrets to reusable workflow
