name: Build Go & SLSA L3 Provenance

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read
  packages: write

jobs:
  build-go-and-provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.1.1
    with:
      go-version: '1.21'
      upload-release-assets: false
      config-path: '.'
    secrets: inherit
