name: Build Go project with SLSA L3 provenance

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read
  packages: write

jobs:
  generate-provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_go_slsa3.yml@v2.1.0
    with:
      go-version: '1.24'
      upload-release-assets: false
      config-path: .
    secrets: inherit
